services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Qbus\Qbevents\:
    resource: '../Classes/*'

  Qbus\Qbevents\Hooks\DataHandlerHooks:
    public: true

  Qbus\Qbevents\Service\EventRecurrenceService:
    public: true
